version: 2
updates:
  - package-ecosystem: npm
    directory: /
    target-branch: next
    schedule:
      interval: weekly
    groups:
      npm:
        patterns: ['*']
        update-types: [minor, patch]
  - package-ecosystem: github-actions
    directory: /
    target-branch: next
    schedule:
      interval: weekly
    groups:
      actions:
        patterns: ['*']
